import { Bounty, User, Submission, Comment, PlatformStats } from "./types";

export const mockUsers: User[] = [
  {
    id: "u1",
    username: "ghost_coder",
    display_name: "Ghost Coder",
    avatar_url: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=ghost",
    bio: "Full-stack dev. I build things that ship.",
    role: "builder",
    reputation: 4820,
    total_earned: 34500,
    total_posted: 0,
    github_url: "https://github.com/ghostcoder",
    created_at: "2025-06-15T00:00:00Z",
  },
  {
    id: "u2",
    username: "vibe_queen",
    display_name: "Vibe Queen",
    avatar_url: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=queen",
    bio: "Startup founder. Shipping fast, paying faster.",
    role: "poster",
    reputation: 3200,
    total_earned: 0,
    total_posted: 72000,
    github_url: "https://github.com/vibequeen",
    created_at: "2025-05-20T00:00:00Z",
  },
  {
    id: "u3",
    username: "byte_wizard",
    display_name: "Byte Wizard",
    avatar_url: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=wizard",
    bio: "React architect. Making the web beautiful one component at a time.",
    role: "builder",
    reputation: 6100,
    total_earned: 52300,
    total_posted: 0,
    github_url: "https://github.com/bytewizard",
    created_at: "2025-04-10T00:00:00Z",
  },
  {
    id: "u4",
    username: "ship_it_sam",
    display_name: "Ship It Sam",
    avatar_url: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=sam",
    bio: "Angel investor and serial builder. Let's build something cool.",
    role: "both",
    reputation: 2800,
    total_earned: 8500,
    total_posted: 45000,
    created_at: "2025-07-01T00:00:00Z",
  },
  {
    id: "u5",
    username: "pixel_punk",
    display_name: "Pixel Punk",
    avatar_url: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=punk",
    bio: "Designer who codes. Code that designs.",
    role: "builder",
    reputation: 3900,
    total_earned: 28700,
    total_posted: 0,
    created_at: "2025-08-12T00:00:00Z",
  },
  {
    id: "u6",
    username: "zero_day",
    display_name: "Zero Day",
    avatar_url: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=zero",
    bio: "Security researcher turned builder. I break things, then build better ones.",
    role: "builder",
    reputation: 5500,
    total_earned: 41200,
    total_posted: 0,
    created_at: "2025-03-22T00:00:00Z",
  },
];

export const mockBounties: Bounty[] = [
  {
    id: "b1",
    poster_id: "u2",
    poster: mockUsers[1],
    title: "AI-Powered SaaS Landing Page",
    brief: "Build a stunning, conversion-optimized landing page for an AI writing tool. Must include hero with animated demo, pricing tiers, testimonials carousel, and a dark/light mode toggle. Framer Motion animations preferred.",
    detailed_spec: "## Requirements\n\n- **Hero Section:** Animated typing effect showing AI generating text\n- **Features Grid:** 6 feature cards with icons and descriptions\n- **Pricing:** 3-tier pricing table (Free, Pro, Enterprise)\n- **Testimonials:** Auto-rotating carousel with user avatars\n- **CTA:** Sticky bottom bar on mobile\n- **Performance:** Lighthouse score > 95\n- **Responsive:** Mobile-first design\n\n## Tech Stack\n- Next.js or Astro\n- Tailwind CSS\n- Framer Motion for animations",
    budget_min: 500,
    budget_max: 1500,
    currency: "USD",
    deadline: "2026-03-15T23:59:59Z",
    status: "open",
    category: "landing-page",
    tags: ["react", "animation", "saas", "responsive"],
    tech_stack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    difficulty: "intermediate",
    max_submissions: 20,
    submission_count: 7,
    visibility: "public",
    created_at: "2026-02-20T10:00:00Z",
    updated_at: "2026-02-20T10:00:00Z",
  },
  {
    id: "b2",
    poster_id: "u4",
    poster: mockUsers[3],
    title: "Real-time Multiplayer Quiz Game",
    brief: "Create a real-time multiplayer quiz game where players join rooms via code, answer timed questions, and see a live leaderboard. Think Kahoot but with a cyberpunk aesthetic.",
    budget_min: 2000,
    budget_max: 5000,
    currency: "USD",
    deadline: "2026-03-30T23:59:59Z",
    status: "open",
    category: "game",
    tags: ["websockets", "real-time", "multiplayer", "game"],
    tech_stack: ["React", "WebSockets", "Node.js"],
    difficulty: "advanced",
    max_submissions: 10,
    submission_count: 3,
    visibility: "public",
    created_at: "2026-02-18T14:30:00Z",
    updated_at: "2026-02-18T14:30:00Z",
  },
  {
    id: "b3",
    poster_id: "u2",
    poster: mockUsers[1],
    title: "Chrome Extension: Tab Manager Pro",
    brief: "Build a Chrome extension that groups, saves, and restores browser tab sessions. Clean UI with search, drag-to-reorder, and keyboard shortcuts. Export/import session configs as JSON.",
    budget_min: 800,
    budget_max: 2000,
    currency: "USD",
    deadline: "2026-03-10T23:59:59Z",
    status: "open",
    category: "chrome-ext",
    tags: ["chrome", "extension", "productivity", "typescript"],
    tech_stack: ["TypeScript", "Chrome APIs", "React"],
    difficulty: "intermediate",
    max_submissions: 15,
    submission_count: 12,
    visibility: "public",
    created_at: "2026-02-15T09:00:00Z",
    updated_at: "2026-02-15T09:00:00Z",
  },
  {
    id: "b4",
    poster_id: "u4",
    poster: mockUsers[3],
    title: "REST API for E-commerce Backend",
    brief: "Build a production-ready REST API for an e-commerce platform. Products, orders, users, cart, payments (Stripe mock), inventory management. Full CRUD with auth middleware and rate limiting.",
    budget_min: 3000,
    budget_max: 7000,
    currency: "USD",
    deadline: "2026-04-01T23:59:59Z",
    status: "open",
    category: "api",
    tags: ["api", "ecommerce", "stripe", "auth"],
    tech_stack: ["Hono.js", "Cloudflare Workers", "D1"],
    difficulty: "expert",
    max_submissions: 8,
    submission_count: 2,
    visibility: "public",
    created_at: "2026-02-22T16:00:00Z",
    updated_at: "2026-02-22T16:00:00Z",
  },
  {
    id: "b5",
    poster_id: "u2",
    poster: mockUsers[1],
    title: "Personal Portfolio with CMS",
    brief: "Build a developer portfolio template with a built-in markdown CMS. Blog posts, project showcase, contact form, resume download. Must be blazing fast and SEO-optimized.",
    budget_min: 300,
    budget_max: 800,
    currency: "USD",
    deadline: "2026-03-20T23:59:59Z",
    status: "open",
    category: "web-app",
    tags: ["portfolio", "cms", "blog", "seo"],
    tech_stack: ["Next.js", "MDX", "Tailwind CSS"],
    difficulty: "beginner",
    max_submissions: 30,
    submission_count: 18,
    visibility: "public",
    created_at: "2026-02-10T12:00:00Z",
    updated_at: "2026-02-10T12:00:00Z",
  },
  {
    id: "b6",
    poster_id: "u4",
    poster: mockUsers[3],
    title: "CLI Tool: Git Workflow Automator",
    brief: "Build a CLI tool that automates common git workflows — smart commits with AI-generated messages, branch management, PR creation, changelog generation. Interactive TUI with colors.",
    budget_min: 1000,
    budget_max: 2500,
    currency: "USD",
    deadline: "2026-03-25T23:59:59Z",
    status: "open",
    category: "cli-tool",
    tags: ["cli", "git", "automation", "tui"],
    tech_stack: ["Rust", "clap", "crossterm"],
    difficulty: "advanced",
    max_submissions: 12,
    submission_count: 5,
    visibility: "public",
    created_at: "2026-02-19T08:00:00Z",
    updated_at: "2026-02-19T08:00:00Z",
  },
  {
    id: "b7",
    poster_id: "u2",
    poster: mockUsers[1],
    title: "Mobile App: Habit Tracker",
    brief: "Design and build a habit tracker mobile app with streak tracking, daily reminders, weekly stats charts, and a reward system. Beautiful animations and satisfying micro-interactions.",
    budget_min: 1500,
    budget_max: 4000,
    currency: "USD",
    deadline: "2026-04-10T23:59:59Z",
    status: "open",
    category: "mobile-app",
    tags: ["mobile", "react-native", "health", "habits"],
    tech_stack: ["React Native", "Expo", "Reanimated"],
    difficulty: "intermediate",
    max_submissions: 15,
    submission_count: 4,
    visibility: "public",
    created_at: "2026-02-23T11:00:00Z",
    updated_at: "2026-02-23T11:00:00Z",
  },
  {
    id: "b8",
    poster_id: "u4",
    poster: mockUsers[3],
    title: "Dashboard Analytics UI Kit",
    brief: "Build a comprehensive analytics dashboard with 10+ chart types, data tables with sorting/filtering, KPI cards, and a responsive sidebar layout. Must support real-time data updates.",
    budget_min: 2000,
    budget_max: 5000,
    currency: "USD",
    deadline: "2026-03-28T23:59:59Z",
    status: "in_review",
    category: "web-app",
    tags: ["dashboard", "charts", "data-viz", "ui-kit"],
    tech_stack: ["React", "Recharts", "Tailwind CSS"],
    difficulty: "advanced",
    max_submissions: 10,
    submission_count: 10,
    visibility: "public",
    created_at: "2026-02-05T15:00:00Z",
    updated_at: "2026-02-25T15:00:00Z",
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: "s1",
    bounty_id: "b1",
    builder_id: "u1",
    builder: mockUsers[0],
    bounty: mockBounties[0],
    title: "Sleek AI Landing - Glassmorphism Edition",
    description: "Built with Next.js 15 and Framer Motion. Features a custom typing animation engine, responsive pricing cards with hover effects, and a testimonial carousel with gesture support.",
    preview_url: "https://s1.submissions.vibe-bounty.pages.dev",
    repo_url: "https://github.com/ghostcoder/ai-landing",
    status: "live",
    tech_used: ["Next.js", "Tailwind CSS", "Framer Motion"],
    submitted_at: "2026-02-22T14:00:00Z",
    deployed_at: "2026-02-22T14:02:00Z",
  },
  {
    id: "s2",
    bounty_id: "b1",
    builder_id: "u3",
    builder: mockUsers[2],
    bounty: mockBounties[0],
    title: "NeonType AI - Cyberpunk Landing",
    description: "A cyberpunk-themed landing with neon gradients, parallax scrolling, and a 3D product mockup section. Fully responsive with 98 Lighthouse score.",
    preview_url: "https://s2.submissions.vibe-bounty.pages.dev",
    status: "live",
    score: 9,
    feedback: "Incredible work! The animations are buttery smooth and the design is exactly what we needed. Love the attention to mobile responsiveness.",
    tech_used: ["Astro", "Tailwind CSS", "Three.js"],
    submitted_at: "2026-02-23T09:30:00Z",
    deployed_at: "2026-02-23T09:32:00Z",
    reviewed_at: "2026-02-24T10:00:00Z",
  },
  {
    id: "s3",
    bounty_id: "b2",
    builder_id: "u5",
    builder: mockUsers[4],
    bounty: mockBounties[1],
    title: "CyberQuiz - Neon Multiplayer",
    description: "Real-time quiz game with WebSocket rooms, animated question transitions, and a cyberpunk-themed leaderboard. Supports up to 50 players per room.",
    preview_url: "https://s3.submissions.vibe-bounty.pages.dev",
    status: "live",
    tech_used: ["React", "Socket.io", "Express"],
    submitted_at: "2026-02-24T16:00:00Z",
    deployed_at: "2026-02-24T16:03:00Z",
  },
  {
    id: "s4",
    bounty_id: "b5",
    builder_id: "u6",
    builder: mockUsers[5],
    bounty: mockBounties[4],
    title: "DevFolio - Minimal Portfolio",
    description: "Clean, minimal portfolio with MDX blog, project cards with live demos, and a terminal-style about section. Perfect Lighthouse scores across the board.",
    preview_url: "https://s4.submissions.vibe-bounty.pages.dev",
    repo_url: "https://github.com/zeroday/devfolio",
    status: "winner",
    score: 10,
    feedback: "This is exactly what I wanted. Clean, fast, and the terminal about section is genius. Awarded!",
    tech_used: ["Next.js", "MDX", "Tailwind CSS"],
    submitted_at: "2026-02-12T11:00:00Z",
    deployed_at: "2026-02-12T11:01:00Z",
    reviewed_at: "2026-02-14T09:00:00Z",
  },
  {
    id: "s5",
    bounty_id: "b1",
    builder_id: "u5",
    builder: mockUsers[4],
    bounty: mockBounties[0],
    title: "Aurora AI - Gradient Masterpiece",
    description: "A beautiful landing page with aurora borealis-inspired gradients, smooth scroll animations, and a unique pricing comparison slider.",
    preview_url: "https://s5.submissions.vibe-bounty.pages.dev",
    status: "pending",
    tech_used: ["Next.js", "Tailwind CSS", "GSAP"],
    submitted_at: "2026-02-26T08:00:00Z",
  },
];

export const mockComments: Comment[] = [
  {
    id: "c1",
    bounty_id: "b1",
    user_id: "u1",
    user: mockUsers[0],
    content: "Quick question — should the pricing toggle be monthly/yearly or just monthly?",
    created_at: "2026-02-21T10:00:00Z",
  },
  {
    id: "c2",
    bounty_id: "b1",
    user_id: "u2",
    user: mockUsers[1],
    content: "Monthly/yearly toggle would be great. Also, make sure the hero animation doesn't impact LCP.",
    created_at: "2026-02-21T10:30:00Z",
  },
  {
    id: "c3",
    bounty_id: "b1",
    user_id: "u3",
    user: mockUsers[2],
    content: "Submitted my entry! Used Three.js for a 3D product mockup in the hero. Let me know what you think.",
    created_at: "2026-02-23T09:35:00Z",
  },
  {
    id: "c4",
    bounty_id: "b2",
    user_id: "u5",
    user: mockUsers[4],
    content: "Is there a specific question format you want? Multiple choice, true/false, or open-ended?",
    created_at: "2026-02-20T14:00:00Z",
  },
  {
    id: "c5",
    bounty_id: "b2",
    user_id: "u4",
    user: mockUsers[3],
    content: "Multiple choice for v1. 4 options per question, 15-second timer. Open to creative interpretations of the UI though!",
    created_at: "2026-02-20T14:15:00Z",
  },
];

export const mockStats: PlatformStats = {
  total_bounties: 247,
  total_paid_out: 892500,
  active_builders: 1834,
  open_bounties: 89,
};
